### ISSUE TITLE
[Bug]: No media confgiured

### ISSUE THREAD

**Issue by DanTulovsky** [markaggar/ha-media-card#27]
### Contact Details

dant@wetsnow.com

### What happened?

Hi,

Just upgraded to the 5.0 version that seems to use Media Index Integration.

I am using media-source (specifically with immich).  I don't understand how to add the media-source to the Media Index. It wants a file system path, but how do I find out what the file system path is for a media-source?

Also, if the Media Index integration is optional (I actually didn't have it installed at first), then there is a different bug, as I still got the "No Media Configured" error, even though I can properly select the Media Path in the browser...

<img width="1115" height="1178" alt="Image" src="https://github.com/user-attachments/assets/7cac15c6-9d3f-4afb-9306-4bf436944d78" />

<img width="667" height="654" alt="Image" src="https://github.com/user-attachments/assets/a23004f0-01dc-4835-949d-766fe54b0196" />

Can I provide you with more information?

Installation method Home Assistant Container
Core 2025.11.0
Frontend 20251105.0

<img width="1273" height="470" alt="Image" src="https://github.com/user-attachments/assets/2100ab92-9ca5-4069-869b-892fe61afc32" />

It says 0 files because there are no images under /media ...

### Version

1.0.20

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
I don't see any relevant logs...
```

**Comment by DanTulovsky** [comment]
If I disable index:

<img width="1146" height="1221" alt="Image" src="https://github.com/user-attachments/assets/ca06a1ac-5600-405c-b683-d6286ec415ce" />

**Comment by DanTulovsky** [comment]
It's a built-in integration:
https://www.home-assistant.io/integrations/immich/



──────────────────────────────────────
dan-generated content may be incorrect

**Comment by DanTulovsky** [comment]
```
hui-card-edit-mode.ts:62 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
firstUpdated @ hui-card-edit-mode.ts:62
_$AE @ reactive-element.ts:1551
performUpdate @ reactive-element.ts:1518
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
_$Ev @ reactive-element.ts:1055
S @ reactive-element.ts:1038
i @ lit-element.ts:130
u @ hui-card-edit-mode.ts:25
P @ scoped-custom-element-registry.ts:642
t @ scoped-custom-element-registry.ts:408
u @ lit-html.ts:1218
$ @ lit-html.ts:1639
_$AI @ lit-html.ts:1475
p @ lit-html.ts:1282
$ @ lit-html.ts:1636
_$AI @ lit-html.ts:1475
u @ directive-helpers.ts:197
update @ repeat.ts:341
_$AS @ directive.ts:135
O @ lit-html.ts:1174
_$AI @ lit-html.ts:1452
p @ lit-html.ts:1282
$ @ lit-html.ts:1636
_$AI @ lit-html.ts:1475
F @ lit-html.ts:2278
update @ lit-element.ts:171
performUpdate @ reactive-element.ts:1504
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
set @ reactive-element.ts:789
update @ hui-section.ts:141
performUpdate @ reactive-element.ts:1504
t.performUpdate @ storage.ts:172
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
set @ reactive-element.ts:789
(anonymous) @ hui-view.ts:282
update @ hui-view.ts:279
performUpdate @ reactive-element.ts:1504
t.performUpdate @ storage.ts:172
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
set @ reactive-element.ts:789
updated @ hui-root.ts:717
_$AE @ reactive-element.ts:1553
performUpdate @ reactive-element.ts:1518
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
set @ reactive-element.ts:789
j @ lit-html.ts:1987
_$AI @ lit-html.ts:1927
p @ lit-html.ts:1282
$ @ lit-html.ts:1636
_$AI @ lit-html.ts:1475
F @ lit-html.ts:2278
update @ lit-element.ts:171
performUpdate @ reactive-element.ts:1504
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
set @ reactive-element.ts:789
_updateLovelace @ ha-panel-lovelace.ts:551
setEditMode @ ha-panel-lovelace.ts:477
_enableEditMode @ hui-root.ts:1027
handleEvent @ lit-html.ts:2109
hui-card-edit-mode.ts:62 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
firstUpdated @ hui-card-edit-mode.ts:62
_$AE @ reactive-element.ts:1551
performUpdate @ reactive-element.ts:1518
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
_$Ev @ reactive-element.ts:1055
S @ reactive-element.ts:1038
i @ lit-element.ts:130
u @ hui-card-edit-mode.ts:25
P @ scoped-custom-element-registry.ts:642
t @ scoped-custom-element-registry.ts:408
u @ lit-html.ts:1218
$ @ lit-html.ts:1639
_$AI @ lit-html.ts:1475
p @ lit-html.ts:1282
$ @ lit-html.ts:1636
_$AI @ lit-html.ts:1475
u @ directive-helpers.ts:197
update @ repeat.ts:341
_$AS @ directive.ts:135
O @ lit-html.ts:1174
_$AI @ lit-html.ts:1452
p @ lit-html.ts:1282
$ @ lit-html.ts:1636
_$AI @ lit-html.ts:1475
F @ lit-html.ts:2278
update @ lit-element.ts:171
performUpdate @ reactive-element.ts:1504
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
set @ reactive-element.ts:789
update @ hui-section.ts:141
performUpdate @ reactive-element.ts:1504
t.performUpdate @ storage.ts:172
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
set @ reactive-element.ts:789
(anonymous) @ hui-view.ts:282
update @ hui-view.ts:279
performUpdate @ reactive-element.ts:1504
t.performUpdate @ storage.ts:172
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
set @ reactive-element.ts:789
updated @ hui-root.ts:717
_$AE @ reactive-element.ts:1553
performUpdate @ reactive-element.ts:1518
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
set @ reactive-element.ts:789
j @ lit-html.ts:1987
_$AI @ lit-html.ts:1927
p @ lit-html.ts:1282
$ @ lit-html.ts:1636
_$AI @ lit-html.ts:1475
F @ lit-html.ts:2278
update @ lit-element.ts:171
performUpdate @ reactive-element.ts:1504
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
set @ reactive-element.ts:789
_updateLovelace @ ha-panel-lovelace.ts:551
setEditMode @ ha-panel-lovelace.ts:477
_enableEditMode @ hui-root.ts:1027
handleEvent @ lit-html.ts:2109
installHook.js:1 [FolderProvider] ⚠️ SubfolderQueue returned null item
overrideMethod @ installHook.js:1
getNext @ ha-media-card.js?hacstag=1047647929501:1041
_loadNext @ ha-media-card.js?hacstag=1047647929501:3328
_initializeProvider @ ha-media-card.js?hacstag=1047647929501:3285
await in _initializeProvider
set hass @ ha-media-card.js?hacstag=1047647929501:3175
set @ reactive-element.ts:788
_loadElement @ hui-card.ts:149
load @ hui-card.ts:42
_createCardElement @ hui-section.ts:83
(anonymous) @ hui-section.ts:361
_createCards @ hui-section.ts:360
_initializeConfig @ hui-section.ts:217
willUpdate @ hui-section.ts:111
performUpdate @ reactive-element.ts:1502
t.performUpdate @ storage.ts:172
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
_$Ev @ reactive-element.ts:1055
S @ reactive-element.ts:1038
f @ hui-section.ts:40
P @ scoped-custom-element-registry.ts:642
t @ scoped-custom-element-registry.ts:408
u @ lit-html.ts:1218
$ @ lit-html.ts:1639
_$AI @ lit-html.ts:1475
p @ lit-html.ts:1282
$ @ lit-html.ts:1650
_$AI @ lit-html.ts:1475
F @ lit-html.ts:2278
update @ lit-element.ts:171
performUpdate @ reactive-element.ts:1504
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
_$Ev @ reactive-element.ts:1055
S @ reactive-element.ts:1038
i @ lit-element.ts:130
L @ hui-dialog-edit-card.ts:49
P @ scoped-custom-element-registry.ts:642
t @ scoped-custom-element-registry.ts:408
(anonymous) @ make-dialog-manager.ts:79
Promise.then
d @ make-dialog-manager.ts:78
(anonymous) @ make-dialog-manager.ts:221
a @ fire_event.ts:75
o @ show-edit-card-dialog.ts:20
(anonymous) @ hui-section.ts:296
a @ fire_event.ts:75
_editCard @ hui-card-edit-mode.ts:256
_handleOverlayClick @ hui-card-edit-mode.ts:228
handleEvent @ lit-html.ts:2109
debug?edit=1:1 Autofocus processing was blocked because a document already has a focused element.
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] 💎 hass setter called. Had hass before: false Has provider: false
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] 💎 Triggering provider initialization
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] Initializing provider: folder Config: {media_source_type: 'folder', enable_navigation_zones: true, show_position_indicator: true, show_dots_indicator: true, enable_keyboard_navigation: true, …}
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] 📁 Initializing FolderProvider - mode: random, path: media-source://immich/1084a0ff-82ae-4bda-8f78-6b383443bcab|albums|1a0877ae-2470-453a-826e-fd2f6ca164ca
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] Calling provider.initialize()
ha-media-card.js?hacstag=1047647929501:725 [FolderProvider] Initialize - mode: random recursive: true
ha-media-card.js?hacstag=1047647929501:725 [FolderProvider] Config: {media_source_type: 'folder', enable_navigation_zones: true, show_position_indicator: true, show_dots_indicator: true, enable_keyboard_navigation: true, …}
ha-media-card.js?hacstag=1047647929501:725 [FolderProvider] useMediaIndex: false
ha-media-card.js?hacstag=1047647929501:725 [FolderProvider] Using SubfolderQueue for filesystem scanning
ha-media-card.js?hacstag=1047647929501:725 [FolderProvider] Adapted config for SubfolderQueue: {media_path: 'media-source://immich/1084a0ff-82ae-4bda-8f78-6b38…3bcab|albums|1a0877ae-2470-453a-826e-fd2f6ca164ca', folder_mode: 'random', slideshow_window: 1000, media_type: 'image', folder: {…}, …}
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: 🚀 SubfolderQueue initialized with config: {enabled: true, scan_depth: null, priority_folder_patterns: Array(0), equal_probability_mode: false, estimated_total_photos: null, …}
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: 📋 Priority patterns configured: []
ha-media-card.js?hacstag=1047647929501:725 [FolderProvider] SubfolderQueue created, calling initialize...
ha-media-card.js?hacstag=1047647929501:725 [FolderProvider] cardAdapter config: {media_path: 'media-source://immich/1084a0ff-82ae-4bda-8f78-6b38…3bcab|albums|1a0877ae-2470-453a-826e-fd2f6ca164ca', folder_mode: 'random', slideshow_window: 1000, media_type: 'image', folder: {…}, …}
ha-media-card.js?hacstag=1047647929501:725 [FolderProvider] cardAdapter._debugMode: true
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: 🔍 _checkPathChange called - currentPath: media-source://immich/1084a0ff-82ae-4bda-8f78-6b383443bcab|albums|1a0877ae-2470-453a-826e-fd2f6ca164ca _initializedPath: undefined
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: 📍 Initialized path tracking: media-source://immich/1084a0ff-82ae-4bda-8f78-6b383443bcab|albums|1a0877ae-2470-453a-826e-fd2f6ca164ca
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: 🚀 Starting subfolder queue initialization
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: ⚡ Starting quick scan for all folders
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: 🔍 Discovering subfolders from base path: media-source://immich/1084a0ff-82ae-4bda-8f78-6b383443bcab|albums|1a0877ae-2470-453a-826e-fd2f6ca164ca max depth: null
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: 🏗️ Using hierarchical scan architecture
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: 🔍 Status: Background paused = false
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] 💎 connectedCallback - card attached to DOM
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] 💎 hass setter called. Had hass before: true Has provider: true
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: 📊 At depth 0 found: 0 files, 0 subfolders
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: 🔍 Recursion check at depth 0 : subfolders: 0 effectiveMaxDepth: null shouldRecurse: false
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: ✅ Hierarchical scan completed: files processed: 0 files added: 0 folders processed: 0 queue size: 0
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: 📊 discoveredFolders array has 0 folders
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: ✅ Initialize completed via full scan
ha-media-card.js?hacstag=1047647929501:725 [FolderProvider] Initialize returned: true
ha-media-card.js?hacstag=1047647929501:725 [FolderProvider] Queue length after initialize: 0
ha-media-card.js?hacstag=1047647929501:725 [FolderProvider] Discovered folders: 0
ha-media-card.js?hacstag=1047647929501:725 [FolderProvider] ✅ SubfolderQueue initialized - enrichment will happen on-demand
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] Provider initialized: true
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] Loading first media
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] 🎮 auto_advance_mode: "reset" - handling manual navigation
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] 🔄 Resetting auto-refresh timer due to manual navigation (clearing interval undefined, will create new one)
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] 🔄 Auto-advance disabled or not configured: {advanceSeconds: undefined, hasHass: true}
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] ✅ Auto-refresh timer reset complete - old interval: undefined, new interval: undefined
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] Getting next item from provider
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: 🔍 _checkPathChange called - currentPath: media-source://immich/1084a0ff-82ae-4bda-8f78-6b383443bcab|albums|1a0877ae-2470-453a-826e-fd2f6ca164ca _initializedPath: media-source://immich/1084a0ff-82ae-4bda-8f78-6b383443bcab|albums|1a0877ae-2470-453a-826e-fd2f6ca164ca
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: ℹ️ Path unchanged: media-source://immich/1084a0ff-82ae-4bda-8f78-6b383443bcab|albums|1a0877ae-2470-453a-826e-fd2f6ca164ca
ha-media-card.js?hacstag=1047647929501:1815 📂 SubfolderQueue: ❌ No folders available for refill
installHook.js:1 [FolderProvider] ⚠️ SubfolderQueue returned null item
overrideMethod @ installHook.js:1
getNext @ ha-media-card.js?hacstag=1047647929501:1041
_loadNext @ ha-media-card.js?hacstag=1047647929501:3328
_initializeProvider @ ha-media-card.js?hacstag=1047647929501:3285
await in _initializeProvider
set hass @ ha-media-card.js?hacstag=1047647929501:3175
set @ reactive-element.ts:788
_loadElement @ hui-card.ts:149
load @ hui-card.ts:42
_createCardElement @ hui-section.ts:83
(anonymous) @ hui-section.ts:361
_createCards @ hui-section.ts:360
_initializeConfig @ hui-section.ts:217
willUpdate @ hui-section.ts:111
performUpdate @ reactive-element.ts:1502
t.performUpdate @ storage.ts:172
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
set @ reactive-element.ts:789
j @ lit-html.ts:1987
_$AI @ lit-html.ts:1927
p @ lit-html.ts:1282
$ @ lit-html.ts:1636
_$AI @ lit-html.ts:1475
p @ lit-html.ts:1282
$ @ lit-html.ts:1636
_$AI @ lit-html.ts:1475
F @ lit-html.ts:2278
update @ lit-element.ts:171
performUpdate @ reactive-element.ts:1504
scheduleUpdate @ reactive-element.ts:1400
_$EP @ reactive-element.ts:1372
await in _$EP
requestUpdate @ reactive-element.ts:1311
set @ reactive-element.ts:789
_handleConfigChanged @ hui-dialog-edit-card.ts:275
handleEvent @ lit-html.ts:2109
a @ fire_event.ts:75
(anonymous) @ hui-element-editor.ts:110
Promise.then
_setConfig @ hui-element-editor.ts:109
_handleYAMLChanged @ hui-element-editor.ts:338
handleEvent @ lit-html.ts:2109
a @ fire_event.ts:75
_onChange @ ha-yaml-editor.ts:173
handleEvent @ lit-html.ts:2109
a @ fire_event.ts:75
M._onUpdate @ ha-code-editor.ts:728
update @ index.js:7721
(anonymous) @ index.js:7601
dispatch @ index.js:7625
hi @ index.js:4681
si.paste @ index.js:4909
runHandlers @ index.js:4332
handleEvent @ index.js:4322
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] Got item: null
ha-media-card.js?hacstag=1047647929501:2977 [card-wuo9jfztk:no-path] Provider returned null item
 [card-wuo9jfztk:no-path] 💎 hass setter called. Had hass before: true Has provider: true
```

**Comment by markaggar** [comment]
Thanks that helped. Check beta releases in HACS for 5.1-beta1. Hopefully that should fix it. Let me know.  Tx!

**Comment by markaggar** [comment]
Go to HACS, find the media card and re-download (top right dots). Then select a specific release and you'll find the 5.1-beta1

-Mark
206-617-8033
________________________________

**Comment by DanTulovsky** [comment]
No luck still doesn't work..I can get you debug logs later today or tomorrow


──────────────────────────────────────
dan-generated content may be incorrect

**Comment by markaggar** [comment]
Fixed in v5.1
